project:
  s3_regional_buckets: true
  name: quickstart-amazon-selling-partner-api-reports-notifications
  owner: quickstart-eng@amazon.com
  regions:
    - us-east-2
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  default:
    template: templates/quick-start-reports-notifications.yml
    parameters:
      AccessKey: override
      SecretKey: override
      RoleArn: override
      ClientId: override
      ClientSecret: override
      ReportStorageNotificationEmail: test@example.com
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-selling-partner-api-reports-notifications/

