== Postdeployment steps

=== Retrieve IAM user credentials to invoke API Gateway endpoints
This Quick Start deploys three API Gateway endpoints and an AWS IAM role and user. You must use the temporary credentials of this user to successfully invoke the endpoints. Complete the following steps to retrieve the user's access keys and the Amazon Resource Name (ARN) of the role.

==== IAM user access keys

. Open the https://console.aws.amazon.com/iam/[AWS IAM console^].
. In the navigation pane, choose *Users*.
. Choose the user named *ApiGatewayInvokeUser*.
. On the *Summary* page for the user, choose the *Security credentials* tab.
. Under *Access keys* choose *Create Access key*.
. Copy the generated *Access key ID* and *Secret access key*, or, choose *Download .csv file*.

==== Role ARN

. Open the https://console.aws.amazon.com/iam/[AWS IAM console^].
. In the navigation pane, choose *Roles*.
. Select the role named *ApiGatewayInvokeRole*.
. On the *ApiGatewayInvokeRole* page, under *Summary*, copy the role *ARN*.

=== Best practices for using {partner-product-short-name} on AWS
For more information about Selling Partner API best practices, see the https://developer-docs.amazon.com/sp-api/docs/what-is-the-selling-partner-api[SP-API Developer Guide^].

=== Security
This Quick Starts implements the following security best practices:

. Application credentials secure storage using AWS Secrets Manager secrets.
. Client token encryption using AWS KMS keys. By using the provided Amazon API Gateway *TokenStorageRestApi* endpoint and/or AWS Lambda *SPAPITokenStorage* function you are following credential encryption best practices.
. API authentication with temporary credentials.
. Least privilege AWS IAM policies.

=== How to use

==== Test using a pre-built Postman collection

Complete the following steps to create and process SP-API reports using a pre-built Postman collection.

==== Set up the Postman collection
. Open the Selling Partner Reports API Quick Start https://documenter.getpostman.com/view/15862940/UyrEhadx[Postman collection documentation page^].
. Choose *Run in Postman* to import the collection to the Postman client application.
. In the imported Postman collection, choose *Variables*.
. Under *CURRENT VALUE*, for *iamUserAccessKey*, enter the *Access key ID* of the IAM user deployed by the Quick Start. To retrieve this, refer to <link to section>.
. For *iamUserSecretKey* enter the *Secret access key* of the IAM user deployed by the Quick Start. To retrieve this, refer to <link to section>.
. For *iamRoleArn*, enter the *ARN* of the IAM role deployed by the Quick Start. To retrieve this, refer to <link to section>.
. Open the https://console.aws.amazon.com/apigateway/[Amazon API Gateway console^].
. In the input search box, type *TokenStorageRestApi*.
. Copy the value under *ID* column.
. In the imported Postman collection, go to *Variables*.
. In *tokenStorageApiId* variable, under *CURRENT VALUE* paste the *TokenStorageRestApi ID* obtained in the previous step.
. Open the https://console.aws.amazon.com/apigateway/[Amazon API Gateway console^].
. In the input search box, type *NotificationsSubscriberRestApi*.
. Copy the value under *ID* column.
. In the imported Postman collection, go to *Variables*.
. In *notificationsSubscriberApiId* variable, under *CURRENT VALUE* paste the *NotificationsSubscriberRestApi ID* obtained in the previous step.
. Open the https://console.aws.amazon.com/apigateway/[Amazon API Gateway console^].
. In the input search box, type *ReportCreatorRestApi*.
. Copy the value under *ID* column.
. In the imported Postman collection, go to *Variables*.
. In *reportCreatorApiId* variable, under *CURRENT VALUE* paste the *ReportCreatorRestApi ID* obtained in the previous step.

==== Invoke the API endpoints
. In the imported Postman collection, select and execute *STS Assume API Gateway Role* request. This request will retrieve temporary credentials from *ApiGatewayInvokeRole* role and automatically store them in collection variables.
. In the imported Postman collection, select *Token Storage* request.
. Select *Body* tab, and replace *SellerId* and *RefreshToken* with seller id and refresh token from the selling partner.
. Submit the request. This request will encrypt and store in the AWS cloud the selling partner's credentials, to be used in subsequent SP-API calls.
. In the imported Postman collection, select *Notifications Subscriber* request.
. Select *Body* tab, and replace *SellerId* with the value used in the previous step. Replace *RegionCode* with the region of the selling partner. Valid values are "NA", "EU" and "FE".
. Submit the request. This request will subscribe your application to *REPORT_PROCESSING_FINISHED* notification for the selling partner specified.
. In the imported Postman collection, select *Report Creator* request.
. Select *Body* tab, and replace *SellerId* and *RegionCode* with the values used in the previous steps. Update the remaining body parameters with valid values of the report you want to create.
. Submit the request. This request will create a report in SP-API; once the report is created, the system will process the incoming notification, store the report locally and notify using the provided email address.

==== Integrate into your product or application

In order to integrate this Quick Start into your product or application, execute the following steps.

==== Get Amazon API Gateway endpoints urls
. Open the https://console.aws.amazon.com/apigateway/[Amazon API Gateway console^].
. Select the API with *Name = TokenStorageRestApi*.
. Go to *Stages* section.
. Expand *prod* stage and click on *POST* under */tokens*.
. Copy the value next to *Invoke URL*.
. Open the https://console.aws.amazon.com/apigateway/[Amazon API Gateway console^].
. Select the API with *Name = NotificationsSubscriberRestApi*.
. Go to *Stages* section.
. Expand *prod* stage and click on *POST* under */notifications*.
. Copy the value next to *Invoke URL*.
. Open the https://console.aws.amazon.com/apigateway/[Amazon API Gateway console^].
. Select the API with *Name = ReportCreatorRestApi*.
. Go to *Stages* section.
. Expand *prod* stage and click on *POST* under */reports*.
. Copy the value next to *Invoke URL*.

==== Invoke the API endpoints
. From your product or application, execute https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html[STS Assume Role API^] using the AWS IAM user's *Access Key* and *Secret Access Key*, and the AWS IAM role ARN obtained while executing the *Post-deployment steps*. This request will retrieve temporary credentials from *ApiGatewayInvokeRole* role to use in the subsequent API calls.
. From your product or application, execute a POST request to *TokenStorageRestApi* using the *Invoke URL* obtained in the previous step. Sign the request using temporary credentials obtained from STS Assume Role. This request will encrypt and store in the AWS cloud the selling partner's credentials, to be used in subsequent SP-API calls. Below you can find a sample request body.
----
{
  "SellerId": "ABC...",
  "RefreshToken": "Atzr|..."
}
----
. From your product or application, execute a POST request to *NotificationsSubscriberRestApi* using the *Invoke URL* obtained in the previous step. Sign the request using temporary credentials obtained from STS Assume Role. This request will subscribe your application to *REPORT_PROCESSING_FINISHED* notification for the selling partner specified. Below you can find a sample request body.
----
{
  "SellerId": "ABC...",
  "RegionCode": "NA|EU|FE",
  "NotificationType": "REPORT_PROCESSING_FINISHED"
}
----
. From your product or application, execute a POST request to *ReportCreatorRestApi* using the *Invoke URL* obtained in the previous step. Sign the request using temporary credentials obtained from STS Assume Role. This request will create a report in SP-API; once the report is created, the system will process the incoming notification, store the report locally and notify using the provided email address. Below you can find a sample request body.
----
{
  "SellerId": "ABC...",
  "RegionCode": "NA|EU|FE",
  "ReportType": "GET_XML_BROWSE_TREE_DATA",
  "MarketplaceIds": "A1F83G8C2ARO7P",
  "ReportDataStartTime": "2022-03-01T09:00:00.000Z",
  "ReportDataEndTime": "2022-03-01T12:00:00.000Z",
  "ReportOptions": "{\"BrowseNodeId\": \"26978488031\"}"
}
----

== Next steps

This Quick Start enables the *REPORT_PROCESSING_FINISHED* notification processing in an AWS Step Functions state machine. This state machine executes four steps: retrieves the report document, stores it, generates a presigned url for it and send an email notification. This workflow covers a basic functionality and is intended to be used as a skeleton for a customized solution adapted to your product's need. In order to do this, extend the provided workflow by adding or removing https://docs.aws.amazon.com/step-functions/latest/dg/concepts-states.html[states^] to it.
